/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;
import java.sql.*;
import javax.crypto.AEADBadTagException;
import javax.swing.table.DefaultTableModel;
import negocio.*;
/**
 *
 * @author ERICKPC
 */
public class frmControlUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form frmControlUsuarios
     */
    DefaultTableModel modelo;
    clsNAdministrador objNAdm = new clsNAdministrador();
    
    public frmControlUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbUsuarios = new javax.swing.JTable();
        btnVol = new javax.swing.JToggleButton();
        btnOrg = new javax.swing.JToggleButton();
        txtusuario = new javax.swing.JTextField();
        btnEstado = new javax.swing.JButton();
        btnid = new javax.swing.JLabel();
        REGRESAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbUsuarios);

        btnVol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/users.png"))); // NOI18N
        btnVol.setText("Voluntarios");
        btnVol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolActionPerformed(evt);
            }
        });

        btnOrg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/red.png"))); // NOI18N
        btnOrg.setText("Organizaciones");
        btnOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrgActionPerformed(evt);
            }
        });

        btnEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/return.png"))); // NOI18N
        btnEstado.setText("Cambiar estado");
        btnEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoActionPerformed(evt);
            }
        });

        btnid.setText(" ");

        REGRESAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        REGRESAR.setText("Regresar MAIN");
        REGRESAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGRESARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVol, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(btnOrg)
                .addGap(131, 131, 131))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(REGRESAR)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(btnid)
                            .addGap(66, 66, 66)
                            .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnEstado))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVol, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEstado)
                    .addComponent(btnid))
                .addGap(18, 18, 18)
                .addComponent(REGRESAR)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolActionPerformed
        // TODO add your handling code here:
        if(btnOrg.isSelected()){
            btnOrg.setSelected(false);
        }
        listarVoluntarios();
        
        //listarVoluntarios();
    }//GEN-LAST:event_btnVolActionPerformed

    private void btnOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrgActionPerformed
        // TODO add your handling code here:
        if(btnVol.isSelected()){
            btnVol.setSelected(false);
        }
        listarOrganizaciones();
        
    }//GEN-LAST:event_btnOrgActionPerformed

    private void tbUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUsuariosMouseClicked
        // TODO add your handling code here:
        int filaSeleccionada = tbUsuarios.getSelectedRow();
        int columna = tbUsuarios.getSelectedColumn();
        if(filaSeleccionada >= 0 && columna >= 0){
            btnid.setText(String.valueOf((int) tbUsuarios.getValueAt(filaSeleccionada, 0)));
            txtusuario.setText((String) tbUsuarios.getValueAt(filaSeleccionada, 1));
        }
    }//GEN-LAST:event_tbUsuariosMouseClicked

    private void btnEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoActionPerformed
        // TODO add your handling code here:
        objNAdm.mtdCambiarEstado(Integer.parseInt(btnid.getText()));
        if(btnVol.isSelected()){
            listarVoluntarios();
        }else if(btnOrg.isSelected()){
            listarOrganizaciones();
        }
    }//GEN-LAST:event_btnEstadoActionPerformed

    private void REGRESARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGRESARActionPerformed
            this.dispose();
    frmPrincipal frmPrincipal = new frmPrincipal();
    frmPrincipal.setVisible(true);
    }//GEN-LAST:event_REGRESARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmControlUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmControlUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmControlUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmControlUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmControlUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton REGRESAR;
    private javax.swing.JButton btnEstado;
    private javax.swing.JToggleButton btnOrg;
    private javax.swing.JToggleButton btnVol;
    private javax.swing.JLabel btnid;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbUsuarios;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
    
    private void listarVoluntarios(){
        modelo = new DefaultTableModel();
        modelo.addColumn("ID USUARIO");
        modelo.addColumn("VOLUNTARIO");
        modelo.addColumn("ESTADO");
        tbUsuarios.setModel(modelo);
        ResultSet rs = objNAdm.mtdListarVoluntarios();
        Object[] voluntario = new Object[3];
        try{
            while(rs.next()){
                voluntario[0]=rs.getInt("idusuario");
                voluntario[1]=(rs.getString("nombre")) + " " + (rs.getString("apellido"));
                if(rs.getInt("estado") == 1){
                    voluntario[2] = "Activo";
                }else voluntario[2] = "Inactivo";
                modelo.addRow(voluntario);
            }
        }catch(SQLException e){
            System.out.println("No se puede crear tabla Voluntarios");
        }
        tbUsuarios.setModel(modelo);
        
    }
    private void listarOrganizaciones(){
        modelo = new DefaultTableModel();
        modelo.addColumn("ID USUARIO");
        modelo.addColumn("ORGANIZACION");
        modelo.addColumn("ESTADO");
        tbUsuarios.setModel(modelo);
        ResultSet rs = objNAdm.mtdListarOrganizaciones();
        Object[] organizacion = new Object[3];
        try{
            while(rs.next()){
                organizacion[0]=rs.getInt("idusuario");
                organizacion[1]=rs.getString("nombre");
                if(rs.getInt("estado") == 1){
                    organizacion[2] = "Activo";
                }else organizacion[2] = "Inactivo";
                modelo.addRow(organizacion);
            }
        }catch(SQLException e){
            System.out.println("No se puede crear tabla Organizaciones");
        }
        tbUsuarios.setModel(modelo);
    }


}
