/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import Config.*;
import com.itextpdf.text.BadElementException;
import entidad.*;
import java.awt.BorderLayout;
import java.io.File;
import java.io.IOException;
import negocio.*;
import negocio.clsNGraficos;

import org.jfree.chart.ChartFactory;
import java.sql.SQLException;
import java.text.NumberFormat;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset;

import org.jfree.chart.labels.CategoryItemLabelGenerator;
import org.jfree.chart.labels.CategoryToolTipGenerator;
import org.jfree.chart.labels.StandardCategoryItemLabelGenerator;
import org.jfree.chart.labels.StandardCategoryToolTipGenerator;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.StandardPieSectionLabelGenerator;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.DocumentException;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author fichu
 */
public class frmReporteGrafico extends javax.swing.JFrame {
    private clsNGraficos negocioGraficos;

    /**
     * Creates new form frmReporteGrafico
     */
    public frmReporteGrafico() {
        initComponents();
        negocioGraficos = new clsNGraficos(btnBarras, btnPastel, btnBarras2);
        
        JFreeChart chart = null;
        ChartPanel chartPanel = new ChartPanel(chart); 
        chartPanel.setPreferredSize(new java.awt.Dimension(560, 370));


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        btnBarras = new javax.swing.JButton();
        btnPastel = new javax.swing.JButton();
        btnBarras2 = new javax.swing.JButton();
        btnPdf = new javax.swing.JButton();
        REGRESAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBarras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/favorite.png"))); // NOI18N
        btnBarras.setText("Calificaciones por Usuario");
        btnBarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarrasActionPerformed(evt);
            }
        });

        btnPastel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mail.png"))); // NOI18N
        btnPastel.setText("Chats por Usuario");
        btnPastel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPastelActionPerformed(evt);
            }
        });

        btnBarras2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/users.png"))); // NOI18N
        btnBarras2.setText("Oportunidades por Organización");
        btnBarras2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarras2ActionPerformed(evt);
            }
        });

        btnPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pdf.png"))); // NOI18N
        btnPdf.setText("Descargar Informe");
        btnPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPdfActionPerformed(evt);
            }
        });

        REGRESAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        REGRESAR.setText("Regresar MAIN");
        REGRESAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGRESARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(REGRESAR, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnPastel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBarras2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBarras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPastel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBarras2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(REGRESAR, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarrasActionPerformed
    CategoryDataset dataset = negocioGraficos.obtenerDatosCalificacionesPorUsuarioConNombres();
    
    JFreeChart chart = ChartFactory.createBarChart(
            "Calificaciones por Usuario",
            "Usuario",
            "Cantidad de Calificaciones",
            dataset,
            PlotOrientation.VERTICAL,                         
            true,
            true,
            false
    );

    CategoryPlot plot = chart.getCategoryPlot();
    BarRenderer renderer = (BarRenderer) plot.getRenderer();
    renderer.setBaseItemLabelGenerator(new StandardCategoryItemLabelGenerator("{2}", NumberFormat.getInstance()));
    renderer.setBaseItemLabelsVisible(true);

    JFrame frame = new JFrame("Gráfico de Calificaciones por Usuario");
    frame.setLayout(new BorderLayout());
    ChartPanel chartPanel = new ChartPanel(chart);
    chartPanel.setPreferredSize(new java.awt.Dimension(560, 370));
    frame.add(chartPanel, BorderLayout.CENTER);
    frame.setSize(600, 400);
    frame.setLocationRelativeTo(null);
    frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    frame.setVisible(true);
    }//GEN-LAST:event_btnBarrasActionPerformed

    private void btnPastelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPastelActionPerformed
    DefaultPieDataset dataset = negocioGraficos.obtenerDatosChatsPorUsuario();

    JFreeChart chart = ChartFactory.createPieChart(
            "Chats por Usuario",  
            dataset,              
            true,                 
            true,
            false
    );

    PiePlot plot = (PiePlot) chart.getPlot();
    plot.setLabelGenerator(new CustomPieSectionLabelGenerator());

    JFrame frame = new JFrame("Gráfico de Chats por Usuario");
    frame.setLayout(new BorderLayout());
    ChartPanel chartPanel = new ChartPanel(chart);
    chartPanel.setPreferredSize(new java.awt.Dimension(560, 370));
    frame.add(chartPanel, BorderLayout.CENTER);
    frame.setSize(600, 400);
    frame.setLocationRelativeTo(null);
    frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    frame.setVisible(true);
    }//GEN-LAST:event_btnPastelActionPerformed

    private void btnBarras2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarras2ActionPerformed
            CategoryDataset dataset = negocioGraficos.obtenerDatosOportunidadesPorOrganizacion();
    
    JFreeChart chart = ChartFactory.createBarChart(
            "Oportunidades por Organización",
            "Organización",
            "Cantidad de Oportunidades",
            dataset,
            PlotOrientation.VERTICAL,
            true,
            true,
            false
    );

    JFrame frame = new JFrame("Gráfico de Oportunidades por Organización");
    frame.setLayout(new BorderLayout());
    ChartPanel chartPanel = new ChartPanel(chart);
    chartPanel.setPreferredSize(new java.awt.Dimension(560, 370));
    frame.add(chartPanel, BorderLayout.CENTER);
    frame.setSize(600, 400);
    frame.setLocationRelativeTo(null);
    frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    frame.setVisible(true);
    }//GEN-LAST:event_btnBarras2ActionPerformed

    private void btnPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPdfActionPerformed
      JFileChooser fileChooser = new JFileChooser();

String defaultFileName = "NeedUInformeGrafico" + obtenerFechaDeHoyComoTexto() + ".pdf";
fileChooser.setSelectedFile(new File(defaultFileName));

fileChooser.setDialogTitle("Guardar Informe PDF");
fileChooser.setFileFilter(new FileNameExtensionFilter("Archivos PDF (*.pdf)", "pdf"));

int userSelection = fileChooser.showSaveDialog(this);

if (userSelection == JFileChooser.APPROVE_OPTION) {
    File selectedFile = fileChooser.getSelectedFile();

    String savePath = selectedFile.getAbsolutePath();
    if (!savePath.toLowerCase().endsWith(".pdf")) {
        savePath += ".pdf";
    }

    String informeText = obtenerTextoInformeDinamico();

    try {
        negocioGraficos.generarInformePDF(savePath, informeText);
    } catch (DocumentException | IOException ex) {
        Logger.getLogger(frmReporteGrafico.class.getName()).log(Level.SEVERE, null, ex);
    }
}  
    }//GEN-LAST:event_btnPdfActionPerformed

    private void REGRESARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGRESARActionPerformed
    this.dispose();
    frmPrincipal frmPrincipal = new frmPrincipal();
    frmPrincipal.setVisible(true);
    }//GEN-LAST:event_REGRESARActionPerformed

    
    private String obtenerTextoInformeDinamico() {
    Date fechaActual = new Date();

    SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
    String fechaFormateada = formatoFecha.format(fechaActual);

    String textoInforme = "Fecha izquierda: " + fechaFormateada + "                Fecha derecha: " + fechaFormateada;
    String fecha= fechaFormateada;
    return textoInforme;   
}

    private String obtenerFechaDeHoyComoTexto() {
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyyMMdd");
    LocalDate today = LocalDate.now();
    return formatter.format(today);
}
private CategoryDataset obtenerDatosCalificacionesPorUsuarioConNombres() {
    DefaultCategoryDataset dataset = new DefaultCategoryDataset();
    dataset.addValue(10, "Calificaciones", "Usuario1");
    dataset.addValue(15, "Calificaciones", "Usuario2");
    return dataset;
}

    
    
   class CustomPieSectionLabelGenerator extends StandardPieSectionLabelGenerator {
        @Override
        public String generateSectionLabel(PieDataset dataset, Comparable key) {
            if (dataset != null) {
                int value = (int) dataset.getValue(key);

                double total = 0;
                for (Object currentKey : dataset.getKeys()) {
                    total += dataset.getValue((int) currentKey).doubleValue();
                }

                double percentage = (value / total) * 100.0;

                String categoria = key.toString();
                if (categoria.contains("organizaciones")) {
                    return String.format("%s: %d (%.1f%%)", categoria, value, percentage);
                }
            }
            return super.generateSectionLabel(dataset, key);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReporteGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReporteGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReporteGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReporteGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReporteGrafico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton REGRESAR;
    private javax.swing.JButton btnBarras;
    private javax.swing.JButton btnBarras2;
    private javax.swing.JButton btnPastel;
    private javax.swing.JButton btnPdf;
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables
}
